name: Selenium test with .NET 6 and Chrome on Ubuntu

on: [push]

jobs:
  selenium_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Build project
        run: |
          dotnet build
      - name: Run Selenium tests
        run: |
          dotnet test
