name: Selenium test with .NET 6 and NUnit on Ubuntu

on: [ push ]

jobs:
  selenium_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Build project
        run: |
          dotnet build
      - name: Run Selenium tests with NUnit
        run: |
          dotnet test --logger "trx;LogFileName=test_results.trx;LogFileFormat=nunit2"
        id: selenium
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
        run: |
          find /usr -name "allure-results" -type d
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
