name: Selenium test with .NET 6 and Chrome on Ubuntu

on: [push]

jobs:
  selenium_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Add Google Chrome repository
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
      - name: Set up .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install google-chrome-stable
      - name: Build project
        run: |
          dotnet build
      - name: Run Selenium tests
        run: |
          dotnet test
