name: Selenium test with .NET 6 and NUnit on Ubuntu

on: [push]

jobs:
  selenium_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100
      - name: Set up Allure
        run: |
          sudo apt-get update
          sudo apt-get -y install allure
          find /usr -name "allure" -print | head -1
          mkdir -p $GITHUB_WORKSPACE/bin
          cp /usr/local/allure/bin/allure $GITHUB_WORKSPACE/bin
          echo 'export PATH=$PATH:$GITHUB_WORKSPACE/bin' >> $GITHUB_ENV
          source ~/.bashrc
      - name: Build project
        run: |
          dotnet build
      - name: Run Selenium tests with NUnit
        run: |
          dotnet test --logger "trx;LogFileName=test_results.trx;LogFileFormat=nunit2"
        id: selenium
      - name: Generate Allure report
        if: always()
        run: |
          allure generate test_results.trx --output allure-report
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
